name: Update styles in Figma

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          run_install: false

      - uses: actions/setup-node@v4
        with:
          node-version: ^22.18.0
          cache: pnpm

      - run: pnpm --filter tailwind-config install

      - run: pnpm --filter tailwind-config run build:rest
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
          FIGMA_FILE_KEY: ${{ secrets.FIGMA_FILE_KEY }}

      - uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update styles in Figma
          branch: create-pull-request/update-styles-in-figma
          title: Update styles in Figma by create-pull-request action
